routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/login');

// Authentication Routes...
Route::auth();



Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('company', 'CompanyController');
    Route::resource('employee', 'EmployeeController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'website', 'logo', 'email'];

    /**
     * return placholder if company has no logo
     *
     * @return image uri
     */
    public function getLogoAttribute($logo)
    {

        return is_null($logo) ? "https://ui-avatars.com/api/?name={$this->name}" : '/storage//' . $logo;
    }


    public function employees()
    {

        return $this->hasMany(Employee::class);
    }
}

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'company_id'];


    public function company()
    {

        return $this->belongsTo(Company::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Company;

class CompanyController extends Controller
{
    /**
     * Display a listing of Companies
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $companies = Company::withCount('employees')->paginate(10);

        return view('company.index', compact('companies'));
    }

    /**
     * Show the form for creating a new Company
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('company.create');
    }

    /**
     * Store a newly created Company in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {

        $data = $request->validated();

        if ($request->hasFile('logo')) {
            $data['logo']  = $request->logo->store('logos', 'public');
        }

        $company = Company::create($data);

        return redirect()->route('company.show', ['id' => $company->id])
            ->with('success', 'Company Successfully Created');
    }

    /**
     * Display the specified Company.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {

        $employees = $company->employees()->paginate(10);


        return view('company.show', compact('company', 'employees'));
    }

    /**
     * Show the form for editing the specified Comapny.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {

        return view('company.edit', compact('company'));
    }

    /**
     * Update the specified Company in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyRequest $request, Company $company)
    {

        $data = $request->validated();


        if ($request->hasFile('logo')) {
            $data['logo']  =  $request->logo->store('logos', 'public');
        }

        $company->update($data);

        return redirect()->route('company.show', ['id' => $company->id])
            ->with('success', 'Company Successfully Updated');
    }

    /**
     * Remove the specified company from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Company::destroy($id);

        return redirect()->route('company.index')
            ->with('success', 'Company Successfully Deleted');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;

use App\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the employees.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $employees = Employee::with('company')->paginate(10);

        return view('employee.index', compact('employees'));
    }

    /**
     * Show the form for creating a new employee.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('employee.create');
    }

    /**
     * Store a newly created employee in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {

        $employee = Employee::create($request->validated());

        return redirect()->route('employee.show', ['id' => $employee->id])
            ->with('success', 'Employee Successfully Created');
    }

    /**
     * Display the employee resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {

        $employee->load('company');

        return view('employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified employee.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $employee->load('company');

        return view('employee.edit', compact('employee'));
    }

    /**
     * Update the specified employee in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, Employee $employee)
    {

        $employee->update($request->validated());

        return redirect()->route('employee.show', ['id' => $employee->id])
            ->with('success', 'Employee Successfully Updated');
    }

    /**
     * Remove the specified employee from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Employee::destroy($id);

        return redirect()->route('employee.index')
            ->with('success', 'Employee Successfully Deleted');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/company/create.blade.php
@extends('layouts.app')

@section('content')
@include('partials._company-form' , ['company' => new \App\Company])
@endsection

resources/views/company/edit.blade.php
@extends('layouts.app')

@section('content')
@include('partials._company-form')
@endsection

resources/views/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('partials._delete-modal')


    <a href="{{ route('company.create') }}" class="btn btn-primary float-right" style="margin-bottom:2em;">New Company</a>

    <table class="table  table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Logo</th>
                <th scope="col"># Employees</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Website</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($companies as $company)
            <tr>
                <td>{{ $company->id }}</td>
                <td> <img src="{{ $company->logo }}" alt="{{ $company->name }}" class="img-thumbnail"> </td>
                <td>{{ $company->employees_count }}</td>
                <td>{{ $company->name }}</td>
                <td>{{ $company->email }}</td>
                <td>
                    <a href="{{ $company->website }}" target="_blank">{{ $company->website }}</a>
                </td>
                <td class="text-right">
                    <div class="btn-group ">
                        <a href="{{ route('company.show' , ['id' => $company->id]) }}" class="btn btn-secondary">
                            Show Full
                        </a>
                        <a href="{{ route('company.edit' , ['id' => $company->id]) }}" class="btn btn-info">
                            Edit
                        </a>

                        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"
                            data-url="{{ route('company.destroy' , ['id' => $company->id]) }}">Delete</button>


                    </div>
                </td>

            </tr>
            @empty
            <tr>
                <td class="text-center" colspan="6">No Companies</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    {{ $companies->links() }}
</div>
@endsection

resources/views/company/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card" style="margin-bottom:2em;">
        <div class="card-header">
            <img src="{{ $company->logo }}" alt="{{ $company->name }}" class="img-thumbnail">
            <p>
                <h2>{{ $company->name }}</h2>
            </p>

        </div>
        <div class="card-body">
            <p>
                <strong>Email:</strong>
                {{ $company->email }}
            </p>
            <p>
                <strong>Website:</strong>
                <a href="{{$company->website}}">{{$company->website}}</a>
            </p>
        </div>
    </div>


    @include('partials._employees-show' , ['company' => $company])
</div>
@endsection

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('content')
@include('partials._employee-form' , ['employee' => new \App\Employee])
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('content')
@include('partials._employee-form')
@endsection

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @include('partials._employees-show')

</div>
@endsection

resources/views/employee/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <strong>Company:</strong>
            <a href="{{ route('company.show' , ['id' => $employee->company->id]) }}" target="_blank">
                {{$employee->company->name}}
            </a>

        </div>
        <div class="card-body">
            <p>
                <strong>First Name:</strong>
                {{ $employee->first_name }}
            </p>
            <p>
                <strong>Last Name:</strong>
                {{ $employee->last_name }}
            </p>
            <p>
                <strong>Email:</strong>
                {{ $employee->email }}
            </p>
            <p>
                <strong>Phone:</strong>
                {{ $employee->phone }}
            </p>
        </div>
    </div>

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>

        @yield('script')

        <!-- Fonts -->
        <link rel="dns-prefetch" href="//fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">


    </head>

    <body>
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('company.index') }}">{{ __('Companies') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('employee.index') }}">{{ __('Employees') }}</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4">
                @yield('content')
            </main>
        </div>

        @include('partials._notification')
    </body>

</html>

resources/views/partials/_company-form.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> {{ $company->exists ? __('Update') :__('Create Company') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ $company->exists ? route('company.update' , ['id' => $company->id]) :route('company.store') }}"
                        enctype="multipart/form-data">
                        @csrf

                        @if($company->exists)
                        @method('PATCH')
                        @endif

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                    name="name" value="{{ old('name') ?? $company->name }}">

                                @if ($errors->has('name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                    name="email" value="{{ old('email') ?? $company->email }}">


                                @if ($errors->has('email'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="logo" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>

                            <div class="col-md-6">
                                <div class="custom-file">
                                    <input type="file" name="logo" class="custom-file-input {{ $errors->has('logo') ? ' is-invalid' : '' }}"
                                        id="logo" accept="image/*">
                                    <label class="custom-file-label" for="logo">
                                        {{ $company->exsist ? 'Choose Logo' : $company->name }}
                                    </label>
                                    @if ($errors->has('logo'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('logo') }}</strong>
                                    </span>
                                    @endif
                                </div>


                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Website') }}</label>

                            <div class="col-md-6">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="website">
                                            http://
                                        </span>
                                    </div>
                                    <input type="text" name="website" class="form-control {{ $errors->has('website') ? ' is-invalid' : '' }}"
                                        id="website" val="{{ old('website') ?? $company->website }}">

                                    @if ($errors->has('website'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('website') }}</strong>
                                    </span>
                                    @endif
                                </div>


                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $company->exists ? __('Update') :__('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<script defer>
    window.addEventListener('load', function () {
        $('#logo').on('change', function () {
            //get the file
            var file = $(this)[0].files[0];

            if (file) {
                $(this).next('.custom-file-label').html(file.name);
            }

        })
    });

</script>

resources/views/partials/_employee-form.blade.php
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"> {{ $employee->exists ? __('Update') :__('Create employee') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ $employee->exists ? route('employee.update' , ['id' => $employee->id]) :route('employee.store') }}"
                        enctype="multipart/form-data">
                        @csrf

                        @if($employee->exists)
                        @method('PATCH')
                        @endif

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name')
                                }}</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control{{ $errors->has('first_name') ? ' is-invalid' : '' }}"
                                    name="first_name" value="{{ old('first_name') ?? $employee->first_name }}">

                                @if ($errors->has('first_name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('first_name') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last
                                Name') }}</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control{{ $errors->has('last_name') ? ' is-invalid' : '' }}"
                                    name="last_name" value="{{ old('last_name') ?? $employee->last_name }}">

                                @if ($errors->has('last_name'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('last_name') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                                    name="email" value="{{ old('email') ?? $employee->email }}">


                                @if ($errors->has('email'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="number" class="form-control{{ $errors->has('phone') ? ' is-invalid' : '' }}"
                                    name="phone" value="{{ old('phone') ?? $employee->phone }}">


                                @if ($errors->has('phone'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('phone') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Company') }}</label>

                            <div class="col-md-6">

                                <select name="company_id" class="custom-select {{ $errors->has('company_id') ? ' is-invalid' : '' }}">
                                    <option>Select Company</option>
                                    @foreach($companies as $company)
                                    <option value="{{ $company->id }}"
                                        {{ ($employee->exists && $employee->company->id == $company->id) || request()->query('c') == $company->id ? 'selected' : ''}}>
                                        {{ $company->name }}
                                    </option>
                                    @endforeach
                                </select>



                                @if ($errors->has('company_id'))
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $errors->first('company_id') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>






                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $employee->exists ? __('Update') :__('Create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/_employees-show.blade.php
<a href="{{ route('employee.create') }}{{ isset($company) ? '?c=' . $company->id : '' }}" class="btn btn-primary float-right"
    style="margin-bottom:2em;">New
    employee</a>

<table class="table  table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            @if(!isset($company))
            <th scope="col">Company</th>
            @endif
            <th scope="col" class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @forelse($employees as $employee)
        <tr>
            <td>{{ $employee->id }}</td>
            <td>{{ $employee->first_name }}</td>
            <td>{{ $employee->last_name }}</td>
            <td>{{ $employee->email }}</td>
            <td>{{ $employee->phone }}</td>
            @if(!isset($company))
            <td> <a href="
    {{ route('company.show' , ['id' => $employee->company->id]) }}">
                    {{$employee->company->name}}
                </a></td>
            @endif
            <td class="
    text-right">
                <div class="btn-group ">
                    <a href="{{ route('employee.edit' , ['id' => $employee->id]) }}" class="btn btn-info">
                        Edit
                    </a>

                    <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete"
                        data-url="{{ route('employee.destroy' , ['id' => $employee->id]) }}">Delete</button>
                </div>
            </td>

        </tr>
        @empty
        <tr>
            <td class="text-center" colspan="6">No Employees</td>
        </tr>
        @endforelse
    </tbody>
</table>

{{ $employees->links() }}

@include('partials._delete-modal')

resources/views/partials/_notification.blade.php
<div aria-live="assertive" aria-atomic="true" style="position: relative; min-height: 200px;">
    <div class="toast" style="position: absolute; top: 0; right: 0;">
        @if(session()->has('success'))
        <div class="toast-body">
            {{ session()->get('success')}}
        </div>
        @endif
    </div>
</div>

@if(session()->has('success'))
<script>
    window.addEventListener('load', function () {
        $('.toast').toast({
            delay: 5000
        });
        $('.toast').toast('show')
    });

</script>
@endif